name: Run XGuardian Scanning

on:
  push:
    branches:
      - main

jobs:
  xguardian-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: XGuardian Scanning
        uses: xmart-xguardian/xguardian-actions@v24.2.1
        env:
            API_EMAIL: ${{ secrets.API_EMAIL }}
            API_PASSWORD: ${{ secrets.API_PASSWORD }}
            API_TOKEN: ${{ secrets.API_TOKEN }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            APP_NAME: ${{ github.event.repository.name }} # Definir o nome da aplicação como o nome do repositório GitHub
            TEAM_ID: "id-do-seu-time"
            SCAN_VERSION: "nome-do-seu-scan"
            FILE_TYPE: "application/zip"
            UPLOAD_URL: "nome-da-url"


